service: lambda-user-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: app.server
    events:
      - http:
          path: /users
          method: ANY
          cors: true
      - http:
          path: /roles
          method: GET
          cors: true
      - http:
          path: /locations
          method: ANY
          cors: true
      - http:
          path: /characters
          method: ANY
          cors: true
      - http:
          path: /characters/view
          method: GET
          cors: true
      - http:
          path: /sessions
          method: ANY
          cors: true
      - http:
          path: /sessions/view
          method: GET
          cors: true
      - http:
          path: /adventures
          method: ANY
          cors: true
      - http:
          path: /adventures/view
          method: GET
          cors: true
      - http:
          path: /settlements
          method: ANY
          cors: true
      - http:
          path: /login
          method: POST
          cors: true
      - http:
          path: /logout
          method: POST
          cors: true
