service: adventure-time-data-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

custom:
  cors:
    origins:
      - https://main.dmonfkjciylm6.amplifyapp.com
      - http://localhost:3000
    headers:
      - Origin
      - X-Requested-With
      - Content-Type
      - Authorization
      - Accept
      - Access-Control-Allow-Headers
    allowCredentials: true

functions:
  app:
    handler: app.server
    events:
      - http:
          path: /access-rules
          method: GET
          cors: ${self:custom.cors}
      - http:
          path: /users
          method: ANY
          cors: ${self:custom.cors}
      - http:
          path: /user/{id}
          method: ANY
          cors: ${self:custom.cors}
      - http:
          path: /roles
          method: GET
          cors: ${self:custom.cors}
      - http:
          path: /locations
          method: ANY
          cors: ${self:custom.cors}
      - http:
          path: /location/{id}
          method: ANY
          cors: ${self:custom.cors}
      - http:
          path: /locations/view
          method: GET
          cors: ${self:custom.cors}
      - http:
          path: /characters
          method: ANY
          cors: ${self:custom.cors}
      - http:
          path: /character/{id}
          method: ANY
          cors: ${self:custom.cors}
      - http:
          path: /characters/view
          method: GET
          cors: ${self:custom.cors}
      - http:
          path: /sessions
          method: ANY
          cors: ${self:custom.cors}
      - http:
          path: /session/{id}
          method: ANY
          cors: ${self:custom.cors}
      - http:
          path: /sessions/view
          method: GET
          cors: ${self:custom.cors}
      - http:
          path: /adventures
          method: ANY
          cors: ${self:custom.cors}
      - http:
          path: /adventure/{id}
          method: ANY
          cors: ${self:custom.cors}
      - http:
          path: /adventures/view
          method: GET
          cors: ${self:custom.cors}
      - http:
          path: /hexes
          method: ANY
          cors: ${self:custom.cors}
      - http:
          path: /hex/{id}
          method: ANY
          cors: ${self:custom.cors}
      - http:
          path: /settlements
          method: ANY
          cors: ${self:custom.cors}
      - http:
          path: /settlement/{id}
          method: ANY
          cors: ${self:custom.cors}
      - http:
          path: /login
          method: POST
          cors: ${self:custom.cors}
      - http:
          path: /login
          method: GET
          cors: ${self:custom.cors}
      - http:
          path: /logout
          method: POST
          cors: ${self:custom.cors}
